---
name: ci - benchmark

on: pull_request

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install pnpm
        run: sudo npm i pnpm@latest -g
      - name: setup pnpm config registry
        run: pnpm config set registry https://registry.verdaccio.org
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      - name: install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.11.0/hyperfine_1.11.0_amd64.deb
          sudo dpkg -i hyperfine_1.11.0_amd64.deb
      - name: benchmark        
        run: pnpm start:benchmark
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
        shell: bash      
